# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: LoadBalancer
  port: 80

deployment:
  replicaCount: 1
  container:
    image:
      repository: "registry.fastdns.io/fastdns/hello-kubernetes"
      tag: "1.1.1" # uses chart appVersion if not provided
      pullPolicy: Always
    port: 8080
  imagePullSecret: regcred

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

